# Read the documentation: https://github.com/FriendsOfSymfony/FOSElasticaBundle/blob/master/doc/setup.md
fos_elastica:
    clients:
        default: { url: '%env(ELASTICSEARCH_URL)%' }
    indexes:
        contracts:
            finder: ~
            client: default
            types:
                contract:
                    properties:
                        title: ~
                        fullName: { analyzer: russian }
                        address: { analyzer: russian }
                    persistence:
                        driver: orm
                        model: App\Entity\Contract
                        provider: ~
        tariffs:
            finder: ~
            client: default
            types:
                tariff:
                    properties:
                        title: { analyzer: russian }
                    persistence:
                        driver: orm
                        model: App\Entity\Tariff
                        provider: ~
